# Generated by Django 3.1.12 on 2021-11-22 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20211122_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacorausuario',
            name='estado_animo',
            field=models.CharField(choices=[('0', 'Muy triste'), ('1', 'Triste'), ('2', 'Normal'), ('2', 'Feliz'), ('2', 'Muy feliz')], max_length=20, verbose_name='Estado usuario'),
        ),
        migrations.AlterField(
            model_name='calendariousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario'),
        ),
    ]
