# Generated by Django 3.1.12 on 2022-01-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211123_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.png', upload_to='perfiles'),
        ),
    ]
