# Generated by Django 3.0 on 2020-03-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200307_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infousuario',
            options={'ordering': ('-usuario',)},
        ),
    ]
