# Generated by Django 3.0 on 2020-05-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0008_auto_20200316_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesosUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('peso', models.FloatField(verbose_name='Peso en KG')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-usuario',),
            },
        ),
    ]
