# Generated by Django 3.1.12 on 2021-11-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bitacorausuario_calendariousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacorausuario',
            name='buena_digestion',
        ),
        migrations.AddField(
            model_name='bitacorausuario',
            name='buen_suenio',
            field=models.IntegerField(choices=[('0', 'No'), ('1', 'Si')], default=1, verbose_name='¿Buen sueño?'),
            preserve_default=False,
        ),
    ]
