# Generated by Django 3.0 on 2020-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='resultado',
            field=models.IntegerField(choices=[(0, 'Negativo'), (1, 'Positivo')], verbose_name='Resultado del diagnostico'),
        ),
    ]
