# Generated by Django 3.0 on 2020-04-19 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('idDiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('altura', models.FloatField(verbose_name='Altura en CM')),
                ('peso', models.FloatField(verbose_name='Peso en KG')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo')),
                ('pres_hi', models.IntegerField(verbose_name='P.A. Sistólica mmHg')),
                ('pres_lo', models.IntegerField(verbose_name='P.A. Diastólica mmHg')),
                ('fumador', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], verbose_name='Fumador')),
                ('alcoholico', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], verbose_name='Acoholico')),
                ('deporte', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], verbose_name='Hace deporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de diagnóstico')),
                ('resultado', models.IntegerField(verbose_name='Resultado del diagnostico')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-idUsuario',),
            },
        ),
    ]
