# Generated by Django 3.0 on 2020-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0002_auto_20200419_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='colesterol',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Arriba de lo normal'), (2, 'Muy arriba de lo normal')], default=0, verbose_name='Nivel de colesterol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='glucosa',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Arriba de lo normal'), (2, 'Muy arriba de lo normal')], default=0, verbose_name='Nivel de glucosa'),
            preserve_default=False,
        ),
    ]
