# Generated by Django 3.1.12 on 2021-11-07 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosticos', '0003_auto_20200422_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnostico',
            new_name='DiagnosticoCardio',
        ),
        migrations.CreateModel(
            name='DiagnosticoObesidad',
            fields=[
                ('idDiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(choices=[(1, 'Mujer'), (0, 'Hombre')], max_length=1, verbose_name='Genero')),
                ('edad', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('altura', models.FloatField(verbose_name='Altura en M')),
                ('peso', models.FloatField(verbose_name='Peso en KG')),
                ('historial_obesidad', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], verbose_name='Historial de sobrepeso en su familia')),
                ('favc', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], verbose_name='Come frecuentemente alimentos con altos niveles calóricos')),
                ('fcvc', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Siempre')], verbose_name='Come vegetales en sus comidas')),
                ('npc', models.IntegerField(choices=[(1, 'Entre 1 y 2'), (2, 'Tres'), (3, 'Más de tres')], verbose_name='Número de comidas principales al día')),
                ('caec', models.IntegerField(choices=[(1, 'No'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Siempre')], verbose_name='Come algún alimento entre comidas')),
                ('smoke', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], verbose_name='¿Fuma?')),
                ('ch2o', models.IntegerField(choices=[(1, 'Menos de un litro'), (2, 'Entre 1 y 2 litros'), (3, 'Más de 2 litros')], verbose_name='Consumo de agua diario')),
                ('scc', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], verbose_name='Monitorea el número de calorías que consume diario')),
                ('faf', models.IntegerField(choices=[(0, 'No practica'), (1, '1 a 2 días por semana'), (2, '2 a 4 días por semana'), (3, '3 a 5 días por semana')], verbose_name='Frecuencia con la que practica actividad física')),
                ('tue', models.IntegerField(choices=[(0, '0 a 2 horas al día'), (1, '3 a 5 horas al día'), (2, 'Más de 5 horas al día')], verbose_name='Tiempo que usa dispositivos electrónicos al día')),
                ('calc', models.IntegerField(choices=[(1, 'No'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Siempre')], verbose_name='Tiempo que usa dispositivos electrónicos al día')),
                ('mtrans', models.IntegerField(choices=[(1, 'Automóvil'), (2, 'Motocicleta'), (3, 'Bicicleta'), (4, 'Transporte público'), (5, 'Caminar')], verbose_name='Medio de transporte principal')),
                ('nobeyesdad', models.IntegerField(choices=[(1, 'Peso insuficiente'), (2, 'Peso normal'), (3, 'Sobrepeso nivel 1'), (4, 'Sobrepeso nivel 2'), (5, 'Obesidad tipo 1'), (6, 'Obesidad tipo 2'), (7, 'Obesidad tipo 3')], verbose_name='Peso corporal')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-idUsuario',),
            },
        ),
    ]
