# Generated by Django 3.1.13 on 2021-12-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0006_auto_20211130_0102'),
        ('diagnosticos', '0006_auto_20211130_1107'),
    ]

    operations = [
    ]
