# Generated by Django 3.0 on 2020-03-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idGrupo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('subgrupo', models.CharField(max_length=50, null=True)),
                ('energia', models.IntegerField(verbose_name='Energía (kcal)')),
                ('proteina', models.IntegerField(verbose_name='Proteína (g)')),
                ('lipidos', models.IntegerField(verbose_name='Lípidos (g)')),
                ('carbohidratos', models.IntegerField(verbose_name='Hidratos de Carbono (g)')),
            ],
            options={
                'ordering': ('-nombre',),
            },
        ),
    ]
