# Generated by Django 3.1.12 on 2021-09-07 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smae', '0002_auto_20200308_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('idTipoComida', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo Comida')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Comidas',
                'ordering': ('-idTipoComida',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Plan')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('calorias', models.IntegerField(verbose_name='Calorías')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'ordering': ('-idUsuario',),
            },
        ),
        migrations.CreateModel(
            name='Colacion',
            fields=[
                ('idColacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Colacion')),
                ('idAlimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smae.alimento', verbose_name='Id Alimento')),
                ('idPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plan', verbose_name='Id Plan')),
                ('idTipoComida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.tipocomida', verbose_name='Id Tipo Comida')),
            ],
            options={
                'verbose_name_plural': 'Colaciones',
                'ordering': ('-idPlan',),
            },
        ),
    ]
