# Generated by Django 3.0 on 2020-03-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_auto_20200317_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('idTipoComida', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo Comida')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Comidas',
                'ordering': ('-idTipoComida',),
            },
        ),
        migrations.RemoveField(
            model_name='colacion',
            name='idTipoColacion',
        ),
        migrations.DeleteModel(
            name='TipoColacion',
        ),
        migrations.AddField(
            model_name='colacion',
            name='idTipoComida',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planes.TipoComida', verbose_name='Id Tipo Comida'),
            preserve_default=False,
        ),
    ]
