# Generated by Django 3.0 on 2020-03-07 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_infousuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
    ]
