# Generated by Django 3.0 on 2021-09-15 11:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=128)),
                ('cuerpo', ckeditor.fields.RichTextField(blank='True', null='True')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
