# Generated by Django 3.0 on 2021-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='abstract',
            field=models.CharField(default='Resumen del articulo', max_length=120),
        ),
    ]
