# Generated by Django 3.0 on 2021-09-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriblog', '0002_articulo_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
