# Generated by Django 3.0 on 2020-03-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smae', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ('idGrupo',)},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='subgrupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('idAlimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('racion', models.CharField(max_length=50)),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smae.Grupo')),
            ],
            options={
                'ordering': ('idAlimento',),
            },
        ),
    ]
