# Generated by Django 3.0 on 2020-03-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_auto_20200317_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colacion',
            options={'ordering': ('-idPlan',), 'verbose_name_plural': 'Colaciones'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('-idUsuario',), 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='tipocolacion',
            options={'ordering': ('-idTipoColacion',), 'verbose_name_plural': 'Tipos de Colaciones'},
        ),
    ]
